### ISSUE TITLE
Compile error in 1-intro-to-brian-neurons

### ISSUE THREAD

**Issue by lisasogerer** [cne-tum/msne-lsmlsda-2019#21]
Hallo @janfb ,
ich bekomme im Tutorial 1-intro-to-brian-neurons einen compile error in cell 12 bei folgendem Code. Ich habe developer tools geupdated, meine Brian library nochmal installiert und den Laptop neugestartet, aber ich bekomme immer wieder den gleichen Fehler. Hast Du eine Idee wo das Problem liegt? 

system:

- macOSX 10.14.5
- `$ clang --version`: Apple LLVM version 10.0.1 (clang-1001.0.46.4)

```python
start_scope()

tau = 10*ms
eqs = '''
dv/dt = (1-v)/tau : 1
'''

G = NeuronGroup(1, eqs)
run(100*ms)
```

traceback: 
```
INFO       No numerical integration method specified for group 'neurongroup', using method 'exact' (took 0.04s). [brian2.stateupdaters.base.method_choice]
/Users/lisasogerer/Library/Caches/cython/brian_extensions/_cython_magic_552368ac013b9eca26eb4e1c9145824c.cpp:838:14: fatal error: 'complex' file not found
    #include <complex>
             ^~~~~~~~~
1 error generated.
/Users/lisasogerer/Library/Caches/cython/brian_extensions/_cython_magic_a9f920525e7555f586ebfd8fa2212d8b.cpp:838:14: fatal error: 'complex' file not found
    #include <complex>
             ^~~~~~~~~
1 error generated.
---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    117             self.spawn(compiler_so + cc_args + [src, '-o', obj] +
--> 118                        extra_postargs)
    119         except DistutilsExecError as msg:

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    158                           "command %r failed with exit status %d"
--> 159                           % (cmd, exit_status))
    160             elif os.WIFSTOPPED(status):

DistutilsExecError: command '/usr/bin/clang' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/network.py in before_run(self, run_namespace)
    840                 try:
--> 841                     obj.before_run(run_namespace)
    842                 except Exception as ex:

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/groups/group.py in before_run(self, run_namespace)
   1114                                                  override_conditional_write=self.override_conditional_write,
-> 1115                                                  codeobj_class=self.codeobj_class
   1116                                                  )

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/codeobject.py in create_runner_codeobj(group, code, template_name, run_namespace, user_code, variable_indices, name, check_units, needed_variables, additional_variables, template_kwds, override_conditional_write, codeobj_class)
    309                               codeobj_class=codeobj_class,
--> 310                               override_conditional_write=override_conditional_write,
    311                               )

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/devices/device.py in code_object(self, owner, name, abstract_code, variables, template_name, variable_indices, codeobj_class, template_kwds, override_conditional_write)
    335                                 name=name)
--> 336         codeobj.compile()
    337         return codeobj

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/runtime/cython_rt/cython_rt.py in compile(self)
    129             compiler=self.compiler,
--> 130             owner_name=self.owner.name+'_'+self.template_name,
    131             )

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py in create_extension(self, code, force, name, define_macros, include_dirs, library_dirs, runtime_library_dirs, extra_compile_args, extra_link_args, libraries, compiler, owner_name)
    133                                          compiler=compiler,
--> 134                                          key=key)
    135                 # Unlock

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py in _load_module(self, module_path, define_macros, include_dirs, library_dirs, extra_compile_args, extra_link_args, libraries, code, lib_dir, module_name, runtime_library_dirs, compiler, key)
    262                     build_extension.build_lib = lib_dir
--> 263                     build_extension.run()
    264                     if prefs['codegen.runtime.cython.delete_source_files']:

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py in run(self)
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340 

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py in build_extensions(self)
    447         else:
--> 448             self._build_extensions_serial()
    449 

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py in _build_extensions_serial(self)
    472             with self._filter_build_errors(ext):
--> 473                 self.build_extension(ext)
    474 

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py in build_extension(self, ext)
    532                                          extra_postargs=extra_args,
--> 533                                          depends=ext.depends)
    534 

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 

~/anaconda3/envs/lsmlsda/lib/python3.5/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    119         except DistutilsExecError as msg:
--> 120             raise CompileError(msg)
    121 

CompileError: command '/usr/bin/clang' failed with exit status 1

During handling of the above exception, another exception occurred:

BrianObjectException                      Traceback (most recent call last)
<ipython-input-16-88b90c52ec07> in <module>()
      7 
      8 G = NeuronGroup(1, eqs)
----> 9 run(100*ms)

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/units/fundamentalunits.py in new_f(*args, **kwds)
   2373                                                      get_dimensions(newkeyset[k]))
   2374 
-> 2375             result = f(*args, **kwds)
   2376             if 'result' in au:
   2377                 if au['result'] == bool:

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/magic.py in run(duration, report, report_period, namespace, profile, level)
    369     '''
    370     return magic_network.run(duration, report=report, report_period=report_period,
--> 371                              namespace=namespace, profile=profile, level=2+level)
    372 run.__module__ = __name__
    373 

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/magic.py in run(self, duration, report, report_period, namespace, profile, level)
    229         self._update_magic_objects(level=level+1)
    230         Network.run(self, duration, report=report, report_period=report_period,
--> 231                     namespace=namespace, profile=profile, level=level+1)
    232 
    233     def store(self, name='default', filename=None, level=0):

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/base.py in device_override_decorated_function(*args, **kwds)
    276                 return getattr(curdev, name)(*args, **kwds)
    277             else:
--> 278                 return func(*args, **kwds)
    279 
    280         device_override_decorated_function.__doc__ = func.__doc__

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/units/fundamentalunits.py in new_f(*args, **kwds)
   2373                                                      get_dimensions(newkeyset[k]))
   2374 
-> 2375             result = f(*args, **kwds)
   2376             if 'result' in au:
   2377                 if au['result'] == bool:

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/network.py in run(self, duration, report, report_period, namespace, profile, level)
    949             namespace = get_local_namespace(level=level+3)
    950 
--> 951         self.before_run(namespace)
    952 
    953         if len(self.objects)==0:

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/base.py in device_override_decorated_function(*args, **kwds)
    276                 return getattr(curdev, name)(*args, **kwds)
    277             else:
--> 278                 return func(*args, **kwds)
    279 
    280         device_override_decorated_function.__doc__ = func.__doc__

~/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/network.py in before_run(self, run_namespace)
    841                     obj.before_run(run_namespace)
    842                 except Exception as ex:
--> 843                     raise brian_object_exception("An error occurred when preparing an object.", obj, ex)
    844 
    845         # Check that no object has been run as part of another network before

BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/core/network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/groups/group.py", line 1115, in before_run
    codeobj_class=self.codeobj_class
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/codeobject.py", line 310, in create_runner_codeobj
    override_conditional_write=override_conditional_write,
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/devices/device.py", line 336, in code_object
    codeobj.compile()
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/runtime/cython_rt/cython_rt.py", line 130, in compile
    owner_name=self.owner.name+'_'+self.template_name,
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py", line 134, in create_extension
    key=key)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/site-packages/brian2/codegen/runtime/cython_rt/extension_manager.py", line 263, in _load_module
    build_extension.run()
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/lisasogerer/anaconda3/envs/lsmlsda/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/clang' failed with exit status 1

Error encountered with object named "neurongroup_stateupdater".
Object was created here (most recent call only, full details in debug log):
  File "<ipython-input-16-88b90c52ec07>", line 8, in <module>
    G = NeuronGroup(1, eqs)

An error occurred when preparing an object. distutils.errors.CompileError: command '/usr/bin/clang' failed with exit status 1
(See above for original error message and traceback.)
```

**Comment by janfb** [comment]
Hi, ja eine Idee woran es liegt schon: kompilieren des cython codes geht etwas schief. Und das liegt wohl an den Einstellungen auf Deinem laptop. Ein workaround ist, kein cython benutzen in brian (so haben wir es im tutorial auch gemacht): 

```
from brian2 import *
prefs.codegen.target = 'numpy'  # use the Python fallback
```

aus: https://brian2.readthedocs.io/en/stable/user/computation.html

fuer eine langfristige loesung faellt mir leider nur googlen ein.

**Comment by lisasogerer** [comment]
Danke, jetzt funktioniert es.
Das heißt ich nehme das am Anfang immer mit dazu wenn ich mit brian arbeite?

**Comment by janfb** [comment]
ja, das waere eine loesung. Um das problem genauer zu verstehen, koenntest Du auch ein ganz neues conda env aufsetzen, mit python 3.7 und brian2 installieren und es dann nochmal versuchen. dann wird sich zeigen, ob es wirklich an deinem C compiler liegt.
